package(
  default_visibility = ["//visibility:public"],
)

android_library(
  name = "lib",
  manifest = "AndroidManifest.xml",
  exports_manifest = 1,
  srcs = glob(["*.java"]),
  resource_files = glob(["res/**"]),
  deps = [
  ],
)
